#!/bin/bash
# ==============================================================================
# Home Assistant Add-on: Azubi Werkzeug Tracker
# Take down the S6 supervision tree when the app fails
# ==============================================================================

declare exit_code
readonly exit_code=${1}

echo "Azubi Werkzeug Tracker wurde beendet mit Code ${exit_code}"

if [[ "${exit_code}" -ne 0 ]] && [[ "${exit_code}" -ne 256 ]]; then
    echo "Service beendet mit Fehlercode ${exit_code}"
fi
