"""Added manufacturer and price columns

Revision ID: 3cefbb0dbee3
Revises: 449fb7b61987
Create Date: 2026-03-01 12:46:04.932780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cefbb0dbee3'
down_revision = '449fb7b61987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=100), nullable=True))

    with op.batch_alter_table('werkzeug', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('werkzeug', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_werkzeug_name'))
        batch_op.drop_column('price')

    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.drop_column('manufacturer')

    with op.batch_alter_table('azubi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_azubi_name'))

    # ### end Alembic commands ###
