"""Added manufacturer and price columns.

Revision ID: 3cefbb0dbee3
Revises: 449fb7b61987
Create Date: 2026-03-01 12:46:04.932780
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3cefbb0dbee3'
down_revision = '449fb7b61987'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade database schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # Check table 'check'
    if 'check' in tables:
        columns_check = [c['name'] for c in inspector.get_columns('check')]
        if 'manufacturer' not in columns_check:
            with op.batch_alter_table('check', schema=None) as batch_op:
                batch_op.add_column(sa.Column('manufacturer', sa.String(length=100), nullable=True))

    # Check table 'werkzeug'
    if 'werkzeug' in tables:
        columns_werkzeug = [c['name'] for c in inspector.get_columns('werkzeug')]
        if 'price' not in columns_werkzeug:
            with op.batch_alter_table('werkzeug', schema=None) as batch_op:
                batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))


def downgrade():
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('werkzeug', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_werkzeug_name'))
        batch_op.drop_column('price')

    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.drop_column('manufacturer')

    with op.batch_alter_table('azubi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_azubi_name'))

    # ### end Alembic commands ###
