"""Initial migration from db.create_all

Revision ID: 449fb7b61987
Revises:
Create Date: 2026-03-01 12:01:29.893314

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '449fb7b61987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # These indexes are managed by the models and indices might not exist yet
    # Removing redundant drop calls to prevent startup errors
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('werkzeug', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_werkzeug_name'), ['name'], unique=False)

    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_check_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_check_datum'), ['datum'], unique=False)

    with op.batch_alter_table('azubi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_azubi_name'), ['name'], unique=False)

    # ### end Alembic commands ###
