"""Add price column to Check model

Revision ID: ccea2d1d404c
Revises: 3cefbb0dbee3
Create Date: 2026-03-14 23:02:51.054596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccea2d1d404c'
down_revision = '3cefbb0dbee3'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns_check = [c['name'] for c in inspector.get_columns('check')]
    
    if 'price' not in columns_check:
        with op.batch_alter_table('check', schema=None) as batch_op:
            batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.drop_column('price')
    # ### end Alembic commands ###
