services:
  ticket-app:
    container_name: ticket_app

    build:
      context: ./ticketsystem # Verzeichnis in dem der Code und das Dockerfile liegen

      dockerfile: Dockerfile.standalone
    ports:
      - "5001:5000"

    volumes:
      # Links: Pfad auf dem Mini PC (CasaOS Standard) | Rechts: Pfad im Container
      - ./data:/data 
    environment:
      - DATA_DIR=/data
      - FLASK_ENV=production
      - STANDALONE_MODE=true
    restart: unless-stopped
