name: "Azubi Werkzeug Tracker"
version: "1.0.0"
slug: "azubi_werkzeug"
description: "Manage and track tools assigned to apprentices."
url: "https://github.com/home-assistant/addons-example"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  - i386
ingress: true
ingress_port: 5000
panel_icon: mdi:tools
map:
  - config:rw
  - share:rw
options: {}
schema: {}
