"""Added approval workflow fields

Revision ID: 079270ff0a87
Revises: 87091d056c1c
Create Date: 2026-03-25 23:12:15.161599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079270ff0a87'
down_revision = '87091d056c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        # BUG-02: checklist_template_id and its FK were already added in 87091d056c1c
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), server_default='none', nullable=False))
        batch_op.add_column(sa.Column('rejected_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_ticket_rejected_by', 'worker', ['rejected_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_rejected_by', type_='foreignkey')
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('rejected_by_id')
        batch_op.drop_column('approval_status')
        # BUG-02: DO NOT drop checklist_template_id here, it belongs to 87091d056c1c

    # ### end Alembic commands ###
