"""Handwerk_Features

Revision ID: 175380aaff7c
Revises: f174a73594e1
Create Date: 2026-03-24 19:50:50.926766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175380aaff7c'
down_revision = 'f174a73594e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker_team',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('worker_id', 'team_id')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_confidential', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('recurrence_rule', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_recurrence_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_ticket_team', 'team', ['assigned_team_id'], ['id'])
        batch_op.create_foreign_key('fk_ticket_worker', 'worker', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_worker', type_='foreignkey')
        batch_op.drop_constraint('fk_ticket_team', type_='foreignkey')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('next_recurrence_date')
        batch_op.drop_column('recurrence_rule')
        batch_op.drop_column('is_confidential')
        batch_op.drop_column('assigned_team_id')

    op.drop_table('checklist_item')
    op.drop_table('worker_team')
    op.drop_table('team')
    # ### end Alembic commands ###
