"""initial

Revision ID: 4520055a4699
Revises: 
Create Date: 2026-03-20 23:38:59.427081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4520055a4699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use native SQLite 'IF NOT EXISTS' for extreme robustness and to avoid inspection locks
    op.execute('CREATE TABLE IF NOT EXISTS system_settings (key VARCHAR(50) NOT NULL, value VARCHAR(200), PRIMARY KEY (key))')
    
    op.execute('''
        CREATE TABLE IF NOT EXISTS worker (
            id INTEGER NOT NULL, 
            name VARCHAR(50) NOT NULL, 
            pin_hash VARCHAR(128), 
            is_active BOOLEAN, 
            is_admin BOOLEAN, 
            needs_pin_change BOOLEAN, 
            failed_login_count INTEGER, 
            locked_until DATETIME, 
            PRIMARY KEY (id), 
            UNIQUE (name)
        )
    ''')
    
    op.execute('''
        CREATE TABLE IF NOT EXISTS ticket (
            id INTEGER NOT NULL, 
            title VARCHAR(100) NOT NULL, 
            description TEXT, 
            status VARCHAR(20) NOT NULL, 
            priority INTEGER NOT NULL, 
            assigned_to_id INTEGER, 
            created_at DATETIME, 
            updated_at DATETIME, 
            PRIMARY KEY (id), 
            FOREIGN KEY(assigned_to_id) REFERENCES worker (id)
        )
    ''')
    
    op.execute('''
        CREATE TABLE IF NOT EXISTS comment (
            id INTEGER NOT NULL, 
            ticket_id INTEGER NOT NULL, 
            author VARCHAR(50) NOT NULL, 
            author_id INTEGER, 
            text TEXT NOT NULL, 
            created_at DATETIME, 
            PRIMARY KEY (id), 
            FOREIGN KEY(author_id) REFERENCES worker (id), 
            FOREIGN KEY(ticket_id) REFERENCES ticket (id)
        )
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('ticket')
    op.drop_table('worker')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
