"""initial

Revision ID: 4520055a4699
Revises: 
Create Date: 2026-03-20 23:38:59.427081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4520055a4699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    if 'system_settings' not in tables:
        op.create_table('system_settings',
        sa.Column('key', sa.String(length=50), nullable=False),
        sa.Column('value', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('key')
        )
    if 'worker' not in tables:
        op.create_table('worker',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('pin_hash', sa.String(length=128), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('needs_pin_change', sa.Boolean(), nullable=True),
        sa.Column('failed_login_count', sa.Integer(), nullable=True),
        sa.Column('locked_until', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    if 'ticket' not in tables:
        op.create_table('ticket',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('assigned_to_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_to_id'], ['worker.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'comment' not in tables:
        op.create_table('comment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('author', sa.String(length=50), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['worker.id'], ),
        sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('ticket')
    op.drop_table('worker')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
