"""Added checklist dependencies

Revision ID: 463d7e748c53
Revises: 079270ff0a87
Create Date: 2026-03-25 23:23:17.157499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463d7e748c53'
down_revision = '079270ff0a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('depends_on_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_checklist_item_depends_on', 'checklist_item', ['depends_on_item_id'], ['id'])
        batch_op.create_foreign_key('fk_checklist_item_team', 'team', ['assigned_team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_checklist_item_depends_on', type_='foreignkey')
        batch_op.drop_constraint('fk_checklist_item_team', type_='foreignkey')
        batch_op.drop_column('depends_on_item_id')
        batch_op.drop_column('due_date')
        batch_op.drop_column('assigned_team_id')

    # ### end Alembic commands ###
