"""Added Templates

Revision ID: 87091d056c1c
Revises: 71aed8933587
Create Date: 2026-03-25 22:10:51.878928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87091d056c1c'
down_revision = '71aed8933587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_template_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ticket_checklist_template_id', 'checklist_template', ['checklist_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_checklist_template_id', type_='foreignkey')
        batch_op.drop_column('checklist_template_id')

    op.drop_table('checklist_template_item')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###
