"""v1.5.2 hotfix

Revision ID: a5f2b8c9d0e1
Revises: e941544c5368
Create Date: 2026-03-22 02:25:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a5f2b8c9d0e1'
down_revision = 'e941544c5368'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    worker_cols = [r[1] for r in bind.execute(sa.text("PRAGMA table_info(worker)")).fetchall()]
    
    with op.batch_alter_table('worker', schema=None) as batch_op:
        if 'last_active' not in worker_cols:
            batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('last_active')
    # ### end Alembic commands ###
