"""v1.3.0

Revision ID: e941544c5368
Revises: 4520055a4699
Create Date: 2026-03-20 23:40:00.543508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e941544c5368'
down_revision = '4520055a4699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_event', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.String(length=30), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # Data migration: populate 'role' from 'is_admin'
    op.execute("UPDATE worker SET role = 'admin' WHERE is_admin = 1")
    op.execute("UPDATE worker SET role = 'worker' WHERE is_admin = 0 OR is_admin IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('due_date')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('event_type')
        batch_op.drop_column('is_system_event')

    op.drop_table('ticket_tags')
    op.drop_table('attachment')
    op.drop_table('tag')
    # ### end Alembic commands ###
