"""v1.3.0

Revision ID: e941544c5368
Revises: 4520055a4699
Create Date: 2026-03-20 23:40:00.543508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e941544c5368'
down_revision = '4520055a4699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get table info directly via SQL to avoid complex inspection locks on SQLite
    bind = op.get_bind()
    tables = [t[0] for t in bind.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table'")).fetchall()]

    if 'tag' not in tables:
        op.create_table('tag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    if 'attachment' not in tables:
        op.create_table('attachment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(length=255), nullable=False),
        sa.Column('filename', sa.String(length=100), nullable=False),
        sa.Column('mime_type', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'ticket_tags' not in tables:
        op.create_table('ticket_tags',
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
        sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
        sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
        )
    
    # Check for columns via PRAGMA
    comment_cols = [r[1] for r in bind.execute(sa.text("PRAGMA table_info(comment)")).fetchall()]
    with op.batch_alter_table('comment', schema=None) as batch_op:
        if 'is_system_event' not in comment_cols:
            batch_op.add_column(sa.Column('is_system_event', sa.Boolean(), nullable=True))
        if 'event_type' not in comment_cols:
            batch_op.add_column(sa.Column('event_type', sa.String(length=30), nullable=True))

    ticket_cols = [r[1] for r in bind.execute(sa.text("PRAGMA table_info(ticket)")).fetchall()]
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        if 'due_date' not in ticket_cols:
            batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        if 'is_deleted' not in ticket_cols:
            batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    worker_cols = [r[1] for r in bind.execute(sa.text("PRAGMA table_info(worker)")).fetchall()]
    with op.batch_alter_table('worker', schema=None) as batch_op:
        if 'role' not in worker_cols:
            batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # Data migration: populate 'role' from 'is_admin'
    if 'role' in [r[1] for r in bind.execute(sa.text("PRAGMA table_info(worker)")).fetchall()]:
        op.execute("UPDATE worker SET role = 'admin' WHERE is_admin = 1")
        op.execute("UPDATE worker SET role = 'worker' WHERE is_admin = 0 OR is_admin IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('due_date')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('event_type')
        batch_op.drop_column('is_system_event')

    op.drop_table('ticket_tags')
    op.drop_table('attachment')
    op.drop_table('tag')
    # ### end Alembic commands ###
