"""v1.13.0_order_ref_and_reminder

Revision ID: f174a73594e1
Revises: a5f2b8c9d0e1
Create Date: 2026-03-23 23:36:53.739650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f174a73594e1'
down_revision = 'a5f2b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_reference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reminder_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('reminder_date')
        batch_op.drop_column('order_reference')

    # ### end Alembic commands ###
